#ifndef SERVICE_REGISTRY_NOTIFIER_V01_H
#define SERVICE_REGISTRY_NOTIFIER_V01_H

#include <limits.h>

typedef enum {
    QMI_SERVREG_NOTIF_SERVICE_STATE_ENUM_TYPE_MIN_VAL_V01 = INT_MIN,
	QMI_SERVREG_NOTIF_SERVICE_STATE_ENUM_TYPE_MAX_VAL_V01 = INT_MAX,
	SERVREG_NOTIF_SERVICE_STATE_DOWN_V01 = 0x0FFFFFFF,
	SERVREG_NOTIF_SERVICE_STATE_UP_V01 = 0x1FFFFFFF,
	SERVREG_NOTIF_SERVICE_STATE_EARLY_DOWN_V01 = 0x2FFFFFFF,
	SERVREG_NOTIF_SERVICE_STATE_UNINIT_V01 = 0x7FFFFFFF,
} qmi_servreg_notif_service_state_enum_type_v01;

#endif /* SERVICE_REGISTRY_NOTIFIER_V01_H */
